### ISSUE TITLE
int object is not iterable

### ISSUE THREAD

**Issue by opemvbs** [harrcorr/ArchiveOrgLibraryDownloader#1]
Finding pages....
Traceback (most recent call last):
  File "archive.py", line 113, in <module>
    download = GetPagesArray(GetBaseUrl(url),pages)
  File "archive.py", line 77, in GetPagesArray
    if(len(split(maxpages)) == 4):
  File "archive.py", line 45, in split
    for i in string:
TypeError: 'int' object is not iterable

**Comment by harrycorrigan** [comment]
how..... im sorry how tf did u manage that? what inputs did u use what arguments i need more details here like haha

**Comment by opemvbs** [comment]
I think I managed to fix it by changing a few lines here and there

`def split(stringy):
    stringy = str(stringy)
    splitstring = []
    for i in stringy:
        splitstring.append(i)
    return splitstring`

and

`    while(len(split(str(maxpages))) != 4):
        maxpages = "0"+str(maxpages)
    if(len(split(maxpages)) == 4):
        maxpages = "0."+str(maxpages)
    maxpages = float(maxpages)`

 Sorry for confusing you, now the problem is just the file that I'm extracting is not the "right" one. I'm closing this thread now.
